### ISSUE TITLE
argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by vlauciani** [INGV/qml2nllphs#1]
@actarus2971 provando a convertire il file in allegato, si riceve:
```
$ docker run . . .
configparser loaded
Traceback (most recent call last):
  File "/opt/qml2nllphs.py", line 443, in <module>
    print(qml2location(OT,ola,ola_u,olo,olo_u,ode,ode_u,qual,pref_mag,region))
  File "/opt/qml2nllphs.py", line 307, in qml2location
    mindist=float(q['minimum_distance'])*100.0
TypeError: float() argument must be a string or a number, not 'NoneType'
```

Immagino che il problema sia il QuakeML che e' di una 200...

[20180110-025133__18013811__INGV-EVENT.qml.zip](https://github.com/INGV/qml2nllphs/files/5932057/20180110-025133__18013811__INGV-EVENT.qml.zip)

**Comment by actarus2971** [comment]
la versione che ho io sul mac e che risulta pushata (sta nel repository) è corretta (infatti ci sono i try except) e non produce nulla nel caso di questa 200. Forse hai la versione precedente?
Penso di si perché i numeri di linea dell'errore non tornano né con il code del repository né con il mio in locale (la linea 307 dell'errore nel mio codice è la 314 e non dovrebbe dare errore grazie al try/except

**Comment by vlauciani** [comment]
Ok, allora il problema e' stato corretto.

Grazie.
